version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      timezone: UTC
      time: "07:00"
    open-pull-requests-limit: 50
    groups:
      test:
        patterns:
          - "jest"
          - "ts-jest"
          - "benchmark"
          - "@types/benchmark"
      build-lint-and-format:
        patterns:
          - "esbuild"
          - "tsx"
          - "ts-node"
          - "turbo"
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "@bufbuild/license-header"
          - "prettier"
          - "@arethetypeswrong/*"
